### ISSUE TITLE
multiprocessing Connection aborted

### ISSUE THREAD

**Issue by jmwoloso** [yoeo/guesslangtools#3]
Great library! I'm trying to use the cli to create a dataset and after some time I keep getting the following traceback

```
20:49:26 DEBUG: https://github.com:443 "GET /dmvianna/patents/archive/master.zip HTTP/1.1" 302 121
20:49:26 DEBUG: Starting new HTTPS connection (1): codeload.github.com:443
20:49:26 DEBUG: https://codeload.github.com:443 "GET /JacobLeach/snap-testing/zip/master HTTP/1.1" 200 3759
20:49:26 DEBUG: Downloading https://github.com/muhammadhassaanfarooqui/Haskell-Test/archive/master.zip
20:49:26 DEBUG: Starting new HTTPS connection (1): github.com:443
20:49:26 DEBUG: Downloading https://github.com/satnam6502/hpull/archive/master.zip
20:49:26 INFO: --> Processed 36600 repositories...
20:49:26 INFO: --> Processed 36700 repositories...
20:49:26 INFO: --> Processed 36800 repositories...
20:49:26 INFO: --> Processed 36900 repositories...
20:49:26 INFO: --> Processed 37000 repositories...
20:49:26 INFO: --> Processed 37100 repositories...
20:49:26 DEBUG: Starting new HTTPS connection (1): github.com:443
20:49:26 INFO: --> Processed 37200 repositories...
20:49:26 INFO: --> Processed 37300 repositories...
20:49:26 INFO: --> Processed 37400 repositories...
20:49:26 INFO: --> Processed 37500 repositories...
20:49:26 INFO: --> Processed 37600 repositories...
20:49:26 INFO: --> Processed 37700 repositories...
20:49:26 DEBUG: https://github.com:443 "GET /marot/hnars/archive/master.zip HTTP/1.1" 302 116
20:49:26 DEBUG: Starting new HTTPS connection (1): codeload.github.com:443

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/jason/python/python376/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/jason/python/python376/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/jason/python/python376/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/jason/python/python376/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/jason/python/python376/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/jason/python/python376/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/jason/python/python376/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/guesslangtools/common.py", line 217, in _apply
    return method(item, *other_args, **keywords)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/guesslangtools/workflow/compressed_repositories.py", line 114, in _download_repository
    ok, status = download_file(url, path)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/guesslangtools/common.py", line 155, in download_file
    response = requests.get(url, stream=True, timeout=TIMEOUT)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jason/.virtualenvs/code_detection/bin/gltool", line 8, in <module>
    sys.exit(main())
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/guesslangtools/__main__.py", line 90, in main
    run_workflow()
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/guesslangtools/app.py", line 14, in run_workflow
    compressed_repositories.download()
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/guesslangtools/common.py", line 112, in wrapped
    result = func(*args, **kw)
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/guesslangtools/workflow/compressed_repositories.py", line 89, in download
    for step, row in enumerate(pool_imap(_download_repository, rows), 1):
  File "/home/jason/.virtualenvs/code_detection/lib/python3.7/site-packages/guesslangtools/common.py", line 208, in pool_imap
    for result in pool.imap(_apply, iterable):
  File "/usr/local/jason/python/python376/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

```

Is there a way to resume a job if it fails like this?

**Comment by yoeo** [comment]
Hi @jmwoloso 

You are getting this error because Github servers closed the HTTP connection when the `gltool` was downloading the some repositories to extract example files.

Fortunately, you can just relaunch `gltool` with the same parameters and the dataset generation will resume where it stopped.

**Comment by jmwoloso** [comment]
Ok great! Thanks @yoeo
